### ISSUE TITLE
Pyndri function does match its source code

### ISSUE THREAD

**Issue by yzh5239** [teanalab/SWDM#1]
In index.py, some functions you called with `self.index.something`  does not match or exist in Pyndri source codes.

For example
```
TypeError: document_count() takes no arguments (1 given)
```
```
AttributeError: 'Index' object has no attribute 'total_count'
```
Is that because of a specific Pyndri version you are using? I am currently using 0.4.

Thanks in advance.

**Comment by balaneshin** [comment]
I was using our fork of PyIndri:
https://github.com/teanalab/pyndri
which I believe has defined your mentioned function here:
https://github.com/teanalab/pyndri/blob/master/src/pyndri.cpp#L508

**Comment by yzh5239** [comment]
Thanks, that helps a lot.
Probably you could state that in your README.
